'use client'
import {useState} from 'react'
type Lab={title:string,subject:string,grade:string,objective:string,explanation:string,variables:any[],formula:string,steps:string[],questions:string[],simulationType:string}
export default function Home(){
 const [query,setQuery]=useState("Newton's Second Law"),[grade,setGrade]=useState('Grade 7'),[lab,setLab]=useState<Lab|null>(null),[loading,setLoading]=useState(false),[error,setError]=useState(''),[values,setValues]=useState<Record<string,number>>({}),[quiz,setQuiz]=useState<any[]>([])
 async function createLab(){setLoading(true);setError('');setQuiz([]);const r=await fetch('/api/lab',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({query,grade})});const d=await r.json();setLoading(false);if(!r.ok){setError(d.error||'Could not create lab');return};setLab(d);const v:any={};(d.variables||[]).forEach((x:any)=>v[x.name]=x.value);setValues(v)}
 async function createQuiz(){if(!lab)return;const r=await fetch('/api/quiz',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({topic:lab.title,grade})});const d=await r.json();setQuiz(d.questions||[])}
 const acceleration=lab?.variables?.length>=2&&lab.formula.toLowerCase().includes('force')?((values[lab.variables[0].name]||0)/(values[lab.variables[1].name]||1)).toFixed(2):null
 return <div className="app"><aside><div className="brand">🔬 AI Science Lab</div><div className="nav active">Lab Generator</div><div className="nav">My Labs</div><div className="nav">AI Tutor</div><div className="nav">Progress</div></aside><main><h1>Search → Create → Explore → Learn</h1><p className="muted">Ask for a science concept and generate an AI-powered learning laboratory.</p><div className="search"><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="e.g. Create a lab to understand photosynthesis"/><select value={grade} onChange={e=>setGrade(e.target.value)}><option>Grade 6</option><option>Grade 7</option><option>Grade 8</option><option>Grade 9</option><option>Grade 10</option></select><button onClick={createLab}>✨ Create Lab</button></div>{loading&&<div className="card"><h2>🧠 AI is designing your laboratory...</h2><p>Understanding the topic → selecting variables → preparing the experiment.</p></div>}{error&&<div className="error">{error}</div>}{lab&&<div className="grid"><section className="card"><span className="badge">AI GENERATED</span><h2>{lab.title}</h2><p><b>Objective:</b> {lab.objective}</p><div className="scene"><div className="orb">🔬</div></div><h3>Interactive Experiment</h3>{(lab.variables||[]).map((x:any)=><div className="control" key={x.name}><b>{x.name}: {values[x.name]??x.value} {x.unit}</b><input type="range" min={x.min} max={x.max} value={values[x.name]??x.value} onChange={e=>setValues({...values,[x.name]:+e.target.value})}/></div>)}{acceleration&&<div className="result">Calculated result: <b>{acceleration} m/s²</b></div>}<h3>How to explore</h3><ol>{(lab.steps||[]).map((s,i)=><li key={i}>{s}</li>)}</ol></section><section className="card"><span className="badge">AI TEACHER</span><h2>Ask and Learn</h2><div className="ai"><b>Explanation</b><p>{lab.explanation}</p></div><button onClick={createQuiz}>📝 Generate 5-question quiz</button>{quiz.length>0&&<div>{quiz.map((q,i)=><div className="quiz" key={i}><b>{i+1}. {q.question}</b>{q.options?.map((o:string)=><div key={o} className="option">{o}</div>)}<small>Answer: {q.answer}</small></div>)}</div>}</section></div>}{!lab&&!loading&&<div className="examples">{['Newton’s Second Law','Electric Circuits','Photosynthesis','Human Respiratory System','Gravity'].map(x=><button key={x} onClick={()=>setQuery(x)}>{x}</button>)}</div>}<p className="footer">Next production layer: Supabase + curriculum RAG + student memory + 3D simulations + voice.</p></main></div>
}